stages:
  - test
  - staging
  - prod

.extended_deploy:
  image: dtzar/helm-kubectl:3.13
  variables:
    KUBE_CONTEXT: otus/search_engine_deploy:yc-k8s
    name: ${CI_ENVIRONMENT_SLUG}
    host: ${name}.${CI_PAGES_DOMAIN}
    reg: ${CI_REGISTRY}/otus
    repo: https://${CI_SERVER_HOST}/otus
  before_script:
    - kubectl config use-context ${KUBE_CONTEXT}
    - >
      function deploy() {
        mkdir -p search-engine/chats
        helm dep build search-engine
        echo "Deploy helm release $name to $KUBE_NAMESPACE"

        helm upgrade --install --wait --atomic \
          --namespace="$KUBE_NAMESPACE" --create-namespace \
          --set ui.ingress.host="$host" \
          --set ui.image.repository=${reg}/search_engine_ui \
          --set ui.image.tag="$(curl -fsSL ${repo}/search_engine_ui/raw/main/VERSION)" \
          --set crawler.image.repository=${reg}/search_engine_crawler \
          --set crawler.image.tag="$(curl -fsSL ${repo}/search_engine_crawler/raw/main/VERSION)" \
          --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
          "$name" \
          search-engine/
      }

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - env
    - exit 0
  only:
    - triggers
    - branches

staging:
  stage: staging
  variables:
    KUBE_NAMESPACE: staging
  extends: .extended_deploy
  environment:
    name: staging
    url: http://${host}
  script:
    - deploy
  only:
    refs:
      - main
  except:
    - triggers

prod:
  stage: prod
  variables:
    KUBE_NAMESPACE: prod
  extends: .extended_deploy
  environment:
    name: prod
    url: http://${host}
  script:
    - deploy
  when: manual
  only:
    refs:
      - main
  except:
    - triggers
