---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: search-engine
    component: mongo
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: search-engine
    component: mongo
    release: {{ .Release.Name }}
