---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: {{ .Values.URL | default "https://vitkhab.github.io/search_engine_test_site/" }}
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{ .Values.mongoPort | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{ .Values.rabbitHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{ .Values.rabbitQueue | default "crawler" }}
        - name: RMQ_USERNAME
          value: {{ .Values.rabbitUsername | default "guest" }}
        - name: RMQ_PASSWORD
          value: {{ .Values.rabbitPassword | default "guest" }}
        - name: CHECK_INTERVAL
          value: {{ .Values.checkInterval | default "3600" | quote }}
        - name: EXCLUDE_URLS
          value: {{ .Values.excludeUrls | default ".*github.com" }}
