---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crawler.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.service.externalPort }}"
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
