---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: search-engine
    component: ui
    release: {{ .Release.Name }}
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search-engine
    component: ui
    release: {{ .Release.Name }}
